name: 'Setup Bun + Install Dependencies'
description: 'Setup Bun + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2

    - name: 📦 Install Project Dependencies
      run: bun install --frozen-lockfile
      shell: bash
