name: CD

on: # This triggers the workflow when changes are pushed to your repository
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed
  pull_request: # This ensures the workflow also runs for pull requests targeting the main branch.
    types:
      - closed
    branches:
      - main

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

jobs:
  deploy: # This is the fourth job, responsible for the deployment.
    if: github.event.pull_request.merged == true || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4

      - name: 📦 Setup Bun + install deps
        uses: ./.github/actions/setup-bun-install

      # - name: Deploy
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     preCommands: bun run build
      #     command: pages deploy
      #     packageManager: bun
